version: '2'
services:
  gender:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"

    environment:
      - VIRTUAL_HOST=neji.api.lamaterservice.com
      - LETSENCRYPT_HOST=neji.api.lamaterservice.com
    
